[phases.setup]
packages = ["python310", "python310Packages.pip", "nodejs", "npm"]

[phases.install]
commands = [
  "python3 -m pip install --upgrade pip",
  "pip install -r backend/requirements.txt",
  "npm install --prefix frontend"
]

[phases.build]
commands = [
  "npm run build --prefix frontend"
]

[phases.start]
commands = [
  "gunicorn backend.multivanderecommerce.wsgi:application --bind 0.0.0.0:$PORT"
]
