# Generated by Django 5.0.2 on 2024-12-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_image_product_slug_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
