# Generated by Django 5.0.2 on 2025-01-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
