# Generated by Django 5.0.2 on 2025-01-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_order_status_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(null=True, upload_to='product_files'),
        ),
    ]
