# Generated by Django 5.0.2 on 2025-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0, max_length=200, null=True),
        ),
    ]
