# Generated by Django 5.0.2 on 2025-03-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uds_price',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
