# Generated by Django 5.0.2 on 2025-03-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_wishlisht'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlisht',
            new_name='Wishlist',
        ),
    ]
