# Generated by Django 5.0.2 on 2025-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_product_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
