# Generated by Django 5.0.2 on 2025-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_customer_address_customer_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='default_address',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
