# Generated by Django 5.0.2 on 2025-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_customeraddress_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
