# Generated by Django 5.0.2 on 2025-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_vendor_mobile_vendor_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
