# Generated by Django 5.0.2 on 2025-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_product_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='category_img/'),
        ),
    ]
